routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Helpers\Common;
use Illuminate\Support\Facades\Storage;
use App\Helpers\DateHelper;

Route::prefix('admin')->name('admin.')->middleware(['auth'])->group(function () {
    Route::resource('news-events-cats', 'Admin\NewsEventsCatsController');
    Route::resource('news-events', 'Admin\NewsEventsController');
    
    Route::resource('services-cats', 'Admin\ServicesCatsController');
    Route::resource('services', 'Admin\ServicesController');

    Route::resource('contacts', 'Admin\ContactsController');

    Route::post('upload-file', 'Admin\FileController@uploadTmp');
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/gioi-thieu', 'AboutUsController@index');

Route::get('/dich-vu/{category?}', 'ServicesController@index');
Route::get('/dich-vu/{category?}/{slug?}', 'ServicesController@detail');

Route::get('/tin-tuc-su-kien/{category?}', 'NewsEventsController@index');
Route::get('/tin-tuc-su-kien/{category?}/{slug?}', 'NewsEventsController@detail');

Route::get('/lien-he', 'ContactUsController@index');

app/Models/NewsEventsCats.php
<?php

namespace App\Models;

use App\Models\Base;
use Illuminate\Database\Eloquent\Model;
use App\Models\Traits\NewsEventsCatsSearch;

class NewsEventsCats extends Base
{
    use NewsEventsCatsSearch;
    
    protected $table = 'news_events_cats';

    protected $fillable = ["title", "slug", "position", "status"];

}

app/Models/Traits/CommonTrait.php
<?php
namespace App\Models\Traits;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Helpers\Common;
use App\Helpers\Permissions;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;

trait CommonTrait{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function createdUser()
    {
        return $this->belongsTo('App\User', 'create_user', 'email');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function updatedUser()
    {
        return $this->belongsTo('App\User', 'update_user', 'email');
    }

    public function getIdDisplayAttribute() {
        return str_pad($this->id, 5, "0", STR_PAD_LEFT);
    }

    public function getStatusDisplayAttribute(){
        return empty($this->status) ? '<i class="fa fa-ban"></i>' : '<i class="fa fa-check"></i>';
    }

    public function cleanData($txt){
        return Common::cleanData($txt);
    }

    public function resizeImage($urlImage, $w = 300){
        return Common::resizeImage($urlImage, $w);
    }

    public function hasAllPermission($permissions, $permission){
        return Permissions::hasAllPermission($permissions, $permission, $this);
    }

    public function getThumbnailDisplayAttribute(){
        $parsed = parse_url($this->thumbnail);
        if (empty($parsed['scheme'])) {
            return $this->thumbnail ? Storage::url($this->thumbnail) : 'admin/dist/img/noimage.jpg';
        }
        return $this->thumbnail;
    }
}

app/Http/Controllers/Admin/NewsEventsCatsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\NewsEventsCats;

use App\Http\Requests\StoreNewsEventsCats;

class NewsEventsCatsController extends Controller
{
    public $title = 'News - Events Categories';
    public $mod = 'news-events-cats';

    public function index(Request $request){
        $records = NewsEventsCats::search($request)->paginate(20);

        return view('admin.'.$this->mod.'.index', [
            'records' => $records,
            'title' => $this->title,
            'mod' => $this->mod
        ]);
    }

    public function show($id){
        $record = empty($id) ? new NewsEventsCats : NewsEventsCats::find($id);

        $html = (string)view('admin.'.$this->mod.'.edit', [
            'title' => $this->title,
            'mod' => $this->mod,
            'record' => $record,
            'status' => (array)config('constants.status'),
        ]);

        return response()->json(['html' => $html]);
    }

    public function update(StoreNewsEventsCats $request){
        $record = empty($request->id) ? new NewsEventsCats : NewsEventsCats::find($request->id);

        $params = $request->all();

        $params['slug'] = str_slug($params['title']);

        $record->fill($params)->save();

        return response()->json(['st' => 200]);
    }

    public function destroy($id){
        $st = NewsEventsCats::find($id)->delete();
        return response()->json(['html' => $st]);
    }
}

resources/views/admin/news-events-cats/edit.blade.php
<form action="{{url('admin/'.$mod.'/update')}}" method="post" id="form-edit-{{$mod}}">
    {{ csrf_field() }}
    {{ method_field('PUT') }}

    <input type="hidden" name="id" value="{{$record->id}}">

    <!-- Modal Header -->
    <div class="modal-header">
        <h4 class="modal-title">{{empty($record->id)?'Create':'Update'}} {{$title}}</h4>
        <button type="button" class="close btn-close-modal" data-dismiss="modal">&times;</button>
    </div>

    <!-- Modal body -->
    <div class="modal-body">
        <div class="tab-content mt-3">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            @include('admin.components.inputs.text', ['label'=>'Title', 'name'=>'title', 'value'=>$record->title, 'required'=>true, 'colLeft' => 12])
                        </div>
                    </div>
        
                    <div class="row">
                        <div class="col-md-6">
                            @include('admin.components.inputs.text', ['type' =>'number', 'label'=>'Position', 'name'=>'position', 'value'=>$record->position??0, 'required'=>true, 'colLeft' => 4, 'className' => 'mb-0'])
                        </div>
                        <div class="col-md-6">
                            @include('admin.components.inputs.select', ['label'=>'Status', 'name'=>'status', 'value'=>$record->status ?? 1, 'data' => $status, 'required'=>true, 'colLeft' => 4, 'className' => 'mb-0'])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal footer -->
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button data-form-target="#form-edit-{{$mod}}" type="button" class="btn btn-primary btn-submit" auto-close-modal="true" data-form-method ="PUT">OK</button>
    </div>
</form>

<script>
    $(document).ready(function () {

        if($(".dropzone-file").length > 0){
            $(".dropzone-file").dropzone({
                url: "/admin/upload-file",
                sending: function(file, xhr, formData) {
                    formData.append("_token", CSRF_TOKEN);
                },
                success: function(file, res){
                    if(res.status == 200){
                        $('#img-preview img').attr('src', res.url);
                        $('input[name=thumbnail]').val(res.pathTmpFile);
                        $(".close-img-preview").removeClass('hide');
                    }else{
                        $('#img-preview img').attr('src', urlNoImage);
                        $('input[name=thumbnail]').val('');
                        $(".close-img-preview").addClass('hide');
                    }
                }
            });
        }

    });
</script>
    

resources/views/admin/news-events-cats/filter.blade.php
<div class="box-header">

    <div class="row">
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-1 label-filter">Search</div>
                <div class="col-md-11">
                    <form action="">
                        <div class="input-group input-group-sm" style="width: 250px;">
                            <input type="text" name="q" class="form-control pull-right" value="{{request()->q}}" placeholder="Search">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-3 text-right">
            <button type="button" data-action="{{$mod}}/0" data-target="#modal-edit-{{$mod}}" class="ajax-modal btn btn-success"><i class="fa fa-plus"></i> Add New</button>
        </div>
    </div>

</div>

resources/views/admin/news-events-cats/index.blade.php
@extends('layouts.admin')

@section('title', $title)

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {{$title}}
            <small>Danh sách</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{url('admin/dashboard')}}"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li class="active">{{$title}}</li>
        </ol>
    </section>
      
    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    @include('admin.' . $mod . '.filter')
                    @include('admin.' . $mod . '.list')
                </div>
            </div>
        </div>

    </section>
@endsection

@push('modals')
<div class="modal fade" id="modal-edit-{{$mod}}">
    <div class="modal-dialog width-60 modal-dialog-centered">
        <div class="modal-content"></div>
    </div>
</div>
@endpush

resources/views/admin/news-events-cats/list.blade.php
<div class="box-body table-responsive no-padding">
    <table class="table table-hover">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th class="text-center">Position</th>
            <th class="text-center">Status</th>
            <th></th>
        </tr>

        @if (count($records) > 0)
            @foreach ($records as $item)
                <tr>
                    <td>{{$item->id_display}}</td>
                    <td>{{$item->title}}</td>
                    <td class="text-center">{{$item->position}}</td>
                    <td class="text-center">{!!$item->status_display!!}</td>
                    <td class="text-center">
                        <span data-action="{{$mod}}/{{$item->id}}" data-target="#modal-edit-{{$mod}}" class="label pointer label-success ajax-modal">Edit</span>
                        <span data-action="{{$mod}}/{{$item->id}}" data-target="#modal-edit-{{$mod}}" class="label pointer label-danger delete-item ml-5px">Delete</span>
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="5" class="text-center">No data</td>
            </tr>
        @endif
    </table>
</div>
<div class="text-center wrap-pagination">{{$records->links()}}</div>